"""Example: 151 per-class descriptions for CLINC150 — the "+quality" label-text path at scale.

Pass these as `label_texts` (keys = the class names you pass as `labels`). No new model, no training.
Measured on the full CLINC150 test (5500): names 0.6518 -> descriptions 0.6816 (+0.0298, McNemar p<1e-6).
Significant, but note it does NOT fully close the gap to description/encoder-specialised references
(dataless 0.815 / PIE 0.831) — for 151 fine-grained intents a one-line description recovers only part of the
gap. See docs/phases/1.1/. (SNIPS, with only 7 opaque names, gets a much larger +9.1 — see snips_descriptions.py.)

Run:  python examples/clinc_descriptions.py
"""
from quorum import ZeroShotEnsemble

# name -> one-line disambiguating description
CLINC_DESCRIPTIONS = {
    "restaurant reviews": "reading reviews or ratings of a restaurant",
    "nutrition info": "the nutrition facts or nutritional information of a food",
    "account blocked": "why a bank account is blocked or locked",
    "oil change how": "how to change the oil in a car",
    "time": "what the current time is",
    "weather": "the current weather or forecast",
    "redeem rewards": "redeeming credit card reward points",
    "interest rate": "the interest rate on an account or loan",
    "gas type": "what type or grade of gasoline a car needs",
    "accept reservations": "whether a restaurant accepts reservations",
    "smart home": "controlling smart home devices like lights or the thermostat",
    "user name": "asking the assistant what the user's own name is",
    "report lost card": "reporting a lost or missing credit or debit card",
    "repeat": "asking the assistant to repeat what it just said",
    "whisper mode": "switching the assistant into whisper (quiet) mode",
    "what are your hobbies": "asking the assistant about its hobbies",
    "order": "placing a new order for food or an item",
    "jump start": "how to jump start a dead car battery",
    "schedule meeting": "scheduling or setting up a new meeting",
    "meeting schedule": "asking what meetings are already on the schedule",
    "freeze account": "freezing a bank account",
    "what song": "asking the name of the song that is currently playing",
    "meaning of life": "asking about the meaning of life",
    "restaurant reservation": "making a reservation at a restaurant",
    "traffic": "the current traffic conditions",
    "make call": "placing a phone call to someone",
    "text": "sending a text message to someone",
    "bill balance": "the outstanding balance owed on a bill",
    "improve credit score": "how to improve or raise a credit score",
    "change language": "changing the assistant's language",
    "no": "answering no or declining",
    "measurement conversion": "converting between units of measurement",
    "timer": "setting a countdown timer",
    "flip coin": "flipping a coin",
    "do you have pets": "asking whether the assistant has any pets",
    "balance": "the balance available in a bank account",
    "tell joke": "asking the assistant to tell a joke",
    "last maintenance": "when the car was last serviced or maintained",
    "exchange rate": "the currency exchange rate",
    "uber": "requesting a ride such as an Uber",
    "car rental": "renting a car",
    "credit limit": "the credit limit on a credit card",
    "out of scope": "a request that is out of scope or not supported",
    "shopping list": "viewing what is on the shopping list",
    "expiration date": "the expiration date of a card or product",
    "routing": "the bank routing number",
    "meal suggestion": "getting a suggestion for a meal to eat",
    "tire change": "how to change a flat car tire",
    "todo list": "viewing the items on the to-do list",
    "card declined": "why a credit or debit card was declined",
    "rewards balance": "the balance of reward points earned",
    "change accent": "changing the assistant's accent",
    "vaccines": "which vaccines are needed, for example for travel",
    "reminder update": "changing or updating an existing reminder",
    "food last": "how long food will stay good before spoiling",
    "change ai name": "renaming the assistant, changing the AI's name",
    "bill due": "when a bill is due",
    "who do you work for": "asking which company the assistant works for",
    "share location": "sharing the user's location with someone",
    "international visa": "visa requirements for international travel",
    "calendar": "viewing events on the calendar",
    "translate": "translating a word or phrase into another language",
    "carry on": "airline carry-on luggage rules",
    "book flight": "booking a flight",
    "insurance change": "changing an existing insurance policy",
    "todo list update": "adding to or updating the to-do list",
    "timezone": "the time zone of a place",
    "cancel reservation": "cancelling an existing reservation",
    "transactions": "listing recent account transactions",
    "credit score": "the user's credit score",
    "report fraud": "reporting fraud or a fraudulent charge",
    "spending history": "reviewing past spending history",
    "directions": "getting directions to a place",
    "spelling": "how to spell a word",
    "insurance": "information about an insurance policy",
    "what is your name": "asking the assistant its own name",
    "reminder": "setting a reminder",
    "where are you from": "asking where the assistant is from",
    "distance": "the distance to a place",
    "payday": "when the next payday is",
    "flight status": "the status of a flight",
    "find phone": "locating a lost phone",
    "greeting": "a greeting such as hello",
    "alarm": "setting an alarm",
    "order status": "the status of an existing order",
    "confirm reservation": "confirming an existing reservation",
    "cook time": "how long to cook a dish",
    "damaged card": "reporting a damaged credit or debit card",
    "reset settings": "resetting the device or assistant settings",
    "pin change": "changing a card or account PIN",
    "replacement card duration": "how long a replacement card takes to arrive",
    "new card": "requesting a new credit or debit card",
    "roll dice": "rolling dice",
    "income": "the user's income",
    "taxes": "a question about taxes",
    "date": "what today's date is",
    "who made you": "asking who created the assistant",
    "pto request": "requesting paid time off",
    "tire pressure": "the recommended tire pressure",
    "how old are you": "asking the assistant's age",
    "rollover 401k": "rolling over a 401k retirement account",
    "pto request status": "the status of a paid-time-off request",
    "how busy": "how busy or crowded a place is",
    "application status": "the status of an application",
    "recipe": "a recipe for a dish",
    "calendar update": "adding or changing a calendar event",
    "play music": "playing music",
    "yes": "answering yes or confirming",
    "direct deposit": "setting up direct deposit of a paycheck",
    "credit limit change": "changing the credit limit on a card",
    "gas": "finding a gas station or checking the car's fuel level",
    "pay bill": "paying a bill",
    "ingredients list": "the list of ingredients in a recipe or dish",
    "lost luggage": "reporting lost luggage",
    "goodbye": "saying goodbye",
    "what can i ask you": "asking what the assistant is able to do",
    "book hotel": "booking a hotel",
    "are you a bot": "asking whether the assistant is a bot",
    "next song": "skipping to the next song",
    "change speed": "changing the assistant's speaking speed",
    "plug type": "which electrical plug or adapter type a country uses",
    "maybe": "answering maybe or being uncertain",
    "w2": "a question about a W-2 tax form",
    "oil change when": "when the car's oil should next be changed",
    "thank you": "saying thank you",
    "shopping list update": "adding to or updating the shopping list",
    "pto balance": "how much paid time off is remaining",
    "order checks": "ordering new checkbooks or checks",
    "travel alert": "travel alerts or warnings for a destination",
    "fun fact": "asking for a fun fact",
    "sync device": "syncing or connecting a device",
    "schedule maintenance": "scheduling car maintenance",
    "apr": "the annual percentage rate (APR) on a card or loan",
    "transfer": "transferring money between accounts",
    "ingredient substitution": "what to substitute for a cooking ingredient",
    "calories": "the calorie count of a food",
    "current location": "asking what the user's current location is",
    "international fees": "foreign transaction or international fees",
    "calculator": "doing a math calculation",
    "definition": "the definition of a word",
    "next holiday": "when the next holiday is",
    "update playlist": "adding or removing songs from a playlist",
    "mpg": "a car's fuel efficiency in miles per gallon",
    "min payment": "the minimum payment due on a bill",
    "change user name": "changing the user's name",
    "restaurant suggestion": "getting a restaurant recommendation",
    "travel notification": "notifying the bank of upcoming travel",
    "cancel": "cancelling the current action",
    "pto used": "how much paid time off has already been used",
    "travel suggestion": "getting a travel or destination suggestion",
    "change volume": "changing the volume",
}

if __name__ == "__main__":
    labels = list(CLINC_DESCRIPTIONS)
    descriptions = [CLINC_DESCRIPTIONS[name] for name in labels]
    clf = ZeroShotEnsemble()
    text = "when is my paycheck coming"
    proba = clf.predict_proba(text, labels, label_texts=descriptions)
    ranked = sorted(zip(labels, proba), key=lambda kv: kv[1], reverse=True)
    print(f"text: {text!r}")
    for name, p in ranked[:3]:
        print(f"  {p:6.3f}  {name}")
