"""Example: 113 generic per-class descriptions for MTOP (en) — the "+quality" label-text path.

Plain one-line rephrasings of each intent name (anyone can write these; nothing from the dataset).
Pass as `label_texts`. See docs/phases/1.1/.

Run:  python scripts/eval_zeroshot.py --dataset mtop --descriptions
"""
from quorum import ZeroShotEnsemble

MTOP_DESCRIPTIONS = {
    "add time timer": "adding time to a timer",
    "add to playlist music": "adding a song to a playlist",
    "answer call": "answering a phone call",
    "cancel call": "cancelling a call",
    "cancel message": "cancelling a message",
    "create alarm": "setting an alarm",
    "create call": "making a phone call",
    "create playlist music": "creating a music playlist",
    "create reminder": "creating a reminder",
    "create timer": "setting a timer",
    "delete alarm": "deleting an alarm",
    "delete playlist music": "deleting a music playlist",
    "delete reminder": "deleting a reminder",
    "delete timer": "deleting a timer",
    "dislike music": "disliking the current song",
    "disprefer": "saying you would prefer not to",
    "end call": "ending a call",
    "fast forward music": "fast-forwarding the music",
    "follow music": "following an artist or playlist",
    "get age": "asking someone's age",
    "get airquality": "asking about the air quality",
    "get alarm": "asking about a set alarm",
    "get attendee event": "asking who is attending an event",
    "get availability": "asking whether someone is available",
    "get call": "asking about a call",
    "get call contact": "asking who a call is with",
    "get call time": "asking about the time of a call",
    "get category event": "asking the category of an event",
    "get contact": "looking up a contact",
    "get contact method": "asking how to contact someone",
    "get date time event": "asking the date or time of an event",
    "get details news": "asking for details of a news story",
    "get education degree": "asking about someone's degree",
    "get education time": "asking when someone studied",
    "get employer": "asking who someone works for",
    "get employment time": "asking how long someone has worked somewhere",
    "get event": "asking about an event",
    "get gender": "asking someone's gender",
    "get group": "asking about a group",
    "get info contact": "asking for a contact's information",
    "get info recipes": "asking for information about a recipe",
    "get job": "asking about someone's job",
    "get language": "asking what language someone speaks",
    "get life event": "asking about a life event",
    "get life event time": "asking when a life event happened",
    "get location": "asking for a location",
    "get lyrics music": "asking for the lyrics of a song",
    "get major": "asking about someone's field of study",
    "get message": "asking about a message",
    "get message contact": "asking who a message is from",
    "get mutual friends": "asking about mutual friends",
    "get recipes": "asking for a recipe",
    "get reminder": "asking about a reminder",
    "get reminder amount": "asking how many reminders there are",
    "get reminder date time": "asking when a reminder is set for",
    "get reminder location": "asking where a reminder is set for",
    "get stories news": "asking for news stories",
    "get sunrise": "asking about the sunrise time",
    "get sunset": "asking about the sunset time",
    "get timer": "asking about a timer",
    "get track info music": "asking about the current song",
    "get undergrad": "asking about someone's undergraduate studies",
    "get weather": "asking about the weather",
    "help reminder": "asking for help with reminders",
    "hold call": "putting a call on hold",
    "ignore call": "ignoring an incoming call",
    "is true recipes": "asking whether something about a recipe is true",
    "like music": "liking the current song",
    "loop music": "looping the current song",
    "merge call": "merging calls together",
    "pause music": "pausing the music",
    "pause timer": "pausing a timer",
    "play media": "playing media",
    "play music": "playing music",
    "prefer": "saying you prefer an option",
    "previous track music": "going to the previous song",
    "question music": "asking a question about music",
    "question news": "asking a question about the news",
    "remove from playlist music": "removing a song from a playlist",
    "repeat all music": "repeating all songs",
    "repeat all off music": "turning off repeat-all",
    "replay music": "replaying the current song",
    "restart timer": "restarting a timer",
    "resume call": "resuming a call",
    "resume music": "resuming the music",
    "resume timer": "resuming a timer",
    "rewind music": "rewinding the music",
    "send message": "sending a message",
    "set available": "setting your status to available",
    "set default provider calling": "setting the default calling app",
    "set default provider music": "setting the default music app",
    "set rsvp interested": "marking yourself as interested in an event",
    "set rsvp no": "declining an event invitation",
    "set rsvp yes": "accepting an event invitation",
    "set unavailable": "setting your status to unavailable",
    "share event": "sharing an event",
    "silence alarm": "silencing an alarm",
    "skip track music": "skipping to the next song",
    "snooze alarm": "snoozing an alarm",
    "start shuffle music": "turning on shuffle",
    "stop music": "stopping the music",
    "stop shuffle music": "turning off shuffle",
    "subtract time timer": "taking time off a timer",
    "switch call": "switching between calls",
    "unloop music": "turning off looping",
    "update alarm": "changing an alarm",
    "update call": "updating a call",
    "update method call": "changing how a call is made",
    "update reminder": "changing a reminder",
    "update reminder date time": "changing when a reminder is set",
    "update reminder location": "changing where a reminder is set",
    "update reminder todo": "changing a reminder's to-do text",
    "update timer": "changing a timer",
}

if __name__ == "__main__":
    labels = list(MTOP_DESCRIPTIONS)
    clf = ZeroShotEnsemble()
    text = "skip this song"
    proba = clf.predict_proba(text, labels, label_texts=[MTOP_DESCRIPTIONS[l] for l in labels])
    for name, p in sorted(zip(labels, proba), key=lambda kv: -kv[1])[:3]:
        print(f"  {p:6.3f}  {name}")
